[build]
builder = "nixpacks"
# watchPatterns = ["/*.ts"]
nixpacksConfigPath = "nixpacks.toml"
buildCommand = "echo buildng!"

[deploy]
startCommand = "bun run index.ts"
restartPolicyType = "NEVER"
# Runs every 15 minutes
cronSchedule = "*/15 * * * *"
