[build]
builder = "nixpacks"
# watchPatterns = ["/*.ts"]
nixpacksConfigPath = "nixpacks.toml"
buildCommand = "bun build --target=node index.ts --outdir ./build"

[deploy]
startCommand = "bun run build/index.js"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
